### ISSUE TITLE
Transfer ownership to CDX.

### ISSUE THREAD

**Issue by krambuhl** [krambuhl/hairy-machete#7]
When @stoff is able, he will eol the current https://github.com/connectivedx/fuzzy-chainsaw build and replace it with hairy-machete by:
1. Commenting here when he has starting this task, so we know to treat this repo as an archive
2. Git Tag the current FC master commit
3. Create commit with removal of all FC files (Empty repo)
4. Create a 2nd commit in FC with a copy of Hairy Machete files (Init)

**Comment by stoff** [comment]
This is in process

**Comment by stoff** [comment]
Fuzzy Chainsaw code replaced; see https://github.com/connectivedx/fuzzy-chainsaw/commit/f7bceb1ef9ab4dc010fe14e57cbd322efbd76a08.

manually moving tasks, will post final comment when tasks are added to FC repo.

**Comment by stoff** [comment]
All open tasks except this have been manually ported to Fuzzy Chainsaw repo.  I believe this task is complete and can be closed.
